{
    "name": "OneSuite - NextGen Complete Pack",
    "version": "19.0.1.0.0",
    "category": "Productivity",
    "summary": "Complete NextGen OneSuite application pack for Odoo 19 Community",
    "author": "NextGen Technology PNG Limited",
    "website": "https://nextgenpng.net",
    "license": "LGPL-3",
    "depends": [
        "community_plus_sme_trading",
        "onesuite_hub",
        "payment_plan_core",
        "payment_plan_account",
        "payment_plan_reports",
        "smart_approval_workflow",
        "smart_approval_purchase",
        "smart_approval_account",
        "smart_approval_sale",
        "smart_approval_inventory",
        "smart_approval_hr",
        "smart_approval_payment_plan",
        "smart_cpq_builder",
        "smart_cpq_sale",
        "smart_cpq_approval_workflow",
        "smart_subscription_manager",
        "smart_subscription_account",
        "smart_subscription_approval",
        "smart_field_service_suite",
        "smart_fsm_account",
        "smart_fsm_approval_workflow",
        "advanced_procurement_suite",
        "advanced_procurement_purchase",
        "advanced_procurement_approval_workflow",
        "advanced_inventory_optimization",
        "advanced_inventory_purchase",
        "advanced_inventory_procurement",
        "advanced_inventory_approval_workflow"
    ],
    "installable": True,
    "application": True,
}
